name: Web Code quality

on:
  pull_request:
    branches:
      - master
    paths:
      - "web/**"
      - "!**.md"

jobs:
  web-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up node
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x
      - name: cache node_modules
        id: cache-node_modules
        uses: actions/cache@v2.1.4
        with:
          path: web/node_modules
          key: ${{ runner.os }}-web-${{ env.cache-name }}-${{ hashFiles('**/web/package-lock.json') }}
      - name: install dependencies
        working-directory: ./web
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: |
          npm install
      - name: run tests
        working-directory: ./web
        run: |
          npm run test:ci
